### ISSUE TITLE
Issue with FlexEdge

### ISSUE THREAD

**Issue by frederickfogerty** [philcockfield/react-atoms#2]
![image](https://cloud.githubusercontent.com/assets/615334/16543319/89e4f7b2-4122-11e6-985d-46cc9304d1e1.png)

Steps to reproduce:

1. Open clean ui-harness
2. Navigate to react-atoms / FlexEdge

**Comment by philcockfield** [comment]
I see what's going on here.  Looks like an update to React is not complaining about "unknown" props on standard HTML elements.

FlexEdge was using that to take hints it's children on how to display it.

**Comment by philcockfield** [comment]
https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b

**Comment by philcockfield** [comment]
Regarding the first Radium warning: Radium have his the same problem as everyone has with the new behavior of React `15.2.0`.  They are fixing this now: https://github.com/FormidableLabs/radium/issues/759

**Comment by philcockfield** [comment]
Updated in UIHarness release: `v3.14.7`
Fixed with commit: https://github.com/philcockfield/ui-harness/commit/ddd1463e0b3d4ddf71c200dfc8c02a1f20bd972a

The Radium error will just have to disappear when Radium fixes itself (hopefully soon).
